const menu=document.getElementById('menu'),game=document.getElementById('game'),play=document.getElementById('playButton'),player=document.getElementById('player'),interaction=document.getElementById('interaction'),dialogue=document.getElementById('dialogue'),questTitle=document.getElementById('questTitle'),questObjective=document.getElementById('questObjective'),coinLabel=document.getElementById('coinLabel'),letter=document.getElementById('letter'),bread=document.getElementById('bread'),toast=document.getElementById('toast'),inventory=document.getElementById('inventory'),inventoryItems=document.getElementById('inventoryItems'),inventoryButton=document.getElementById('inventoryButton'),closeInventory=document.getElementById('closeInventory'),dayLabel=document.getElementById('dayLabel');
const keys={};const saveKey='luna-pelon-save-v05';let state=JSON.parse(localStorage.getItem(saveKey)||'null')||{x:.5,y:.5,coins:0,inventory:[],quest:'none',letterTaken:false,breadTaken:false,questDone:false,day:1};
let x=Number(state.x)||.5,y=Number(state.y)||.5,lastSave=0,dialogueOpen=false;
const npcs=[{x:.42,y:.42,name:'Vecino'},{x:.73,y:.28,name:'Luna'},{x:.83,y:.55,name:'Almacenero'}];
const obstacles=[{x:.12,y:.20,w:.20,h:.16},{x:.69,y:.47,w:.18,h:.14},{x:.68,y:.17,w:.12,h:.10},{x:.22,y:.61,w:.08,h:.13},{x:.79,y:.69,w:.10,h:.13}];
function save(){state.x=x;state.y=y;localStorage.setItem(saveKey,JSON.stringify(state))}
function say(text){dialogue.textContent=text;dialogue.style.display='block';dialogueOpen=true}
function closeDialogue(){dialogue.style.display='none';dialogueOpen=false}
function notify(text){toast.textContent=text;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function has(name){return state.inventory.some(i=>i.name===name)}
function addItem(name,icon){if(!has(name))state.inventory.push({name,icon})}
function removeItem(name){state.inventory=state.inventory.filter(i=>i.name!==name)}
function updateUI(){
 coinLabel.textContent='🪙 '+state.coins;dayLabel.textContent='DÍA '+state.day+' · '+(state.day%2?'MAÑANA':'TARDE');letter.classList.toggle('taken',state.letterTaken);bread.classList.toggle('taken',state.breadTaken);
 if(state.quest==='none'){questTitle.textContent='Una primera historia';questObjective.textContent='Hablá con el Vecino para descubrir qué necesita.'}
 else if(state.quest==='letter'){questTitle.textContent='Un mensaje para Luna';questObjective.textContent=state.letterTaken?'Llevá la carta a Luna.':'Encontrá la carta cerca de la casa.'}
 else if(state.quest==='deliver'){questTitle.textContent='Un mensaje para Luna';questObjective.textContent='Entregale la carta a Luna.'}
 else if(state.quest==='bread'){questTitle.textContent='Una compra sencilla';questObjective.textContent='Comprá un pan en el Almacén por 5 monedas.'}
 else if(state.quest==='complete'){questTitle.textContent='Historia en marcha';questObjective.textContent='La primera misión terminó. Explorá y descubrí qué sigue.'}
 inventoryItems.innerHTML='';if(!state.inventory.length)inventoryItems.innerHTML='<div class="inventory-item"><span class="icon">·</span><small>Vacío</small></div>';state.inventory.forEach(item=>{const el=document.createElement('div');el.className='inventory-item';el.innerHTML='<span class="icon">'+item.icon+'</span><small>'+item.name+'</small>';inventoryItems.appendChild(el)})
}
play.addEventListener('click',()=>{menu.classList.add('hidden');game.classList.remove('hidden');updateUI();notify('Bienvenido a Luna Pelón')});inventoryButton.addEventListener('click',()=>inventory.classList.remove('hidden'));closeInventory.addEventListener('click',()=>inventory.classList.add('hidden'));dialogue.addEventListener('click',closeDialogue);
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='i'){inventory.classList.toggle('hidden');keys[k]=false}if(k==='escape'){closeDialogue();inventory.classList.add('hidden')}});document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll('.touch-controls button').forEach(b=>{const k=b.dataset.key;const down=e=>{e.preventDefault();keys[k]=true};const up=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)});
function blocked(nx,ny){if(nx<.035||nx>.965||ny<.065||ny>.94)return true;const r=.025;return obstacles.some(o=>nx+r>o.x&&nx-r<o.x+o.w&&ny+r>o.y&&ny-r<o.y+o.h)}
function move(dx,dy){const nx=x+dx,ny=y+dy;if(!blocked(nx,y))x=nx;if(!blocked(x,ny))y=ny}
function interact(){
 const target=getTarget();if(!target)return;
 if(target.type==='letter'){state.letterTaken=true;state.quest='deliver';addItem('Carta','✉️');save();updateUI();notify('Conseguiste la carta');say('Encontraste una carta. Alguien está esperando este mensaje.');return}
 if(target.type==='bread'){if(state.quest==='bread'&&state.coins>=5){state.coins-=5;state.breadTaken=true;addItem('Pan','🥖');state.quest='complete';save();updateUI();notify('Compraste pan · -5 monedas');say('Almacenero: “Listo. Un pan recién hecho. Que lo disfrutes.”');return}say(state.coins<5?'Almacenero: “Te faltan monedas para comprar el pan.”':'Almacenero: “Si necesitás algo, avisame.”');return}
 const n=target.data;
 if(n.name==='Vecino'){if(state.quest==='none'){state.quest='letter';save();updateUI();say('Vecino: “Necesito hacerle llegar una carta a Luna. ¿Podés ayudarme?”');return}if(state.quest==='letter'){say('Vecino: “La carta está cerca de mi casa. Buscala y después llevásela a Luna.”');return}if(state.quest==='deliver'){say('Vecino: “Luna debería estar por el otro lado del pueblo.”');return}say('Vecino: “Todavía queda mucho pueblo por conocer.”');return}
 if(n.name==='Luna'){if(state.quest==='deliver'&&has('Carta')){removeItem('Carta');state.quest='bread';state.questDone=true;state.coins+=25;addItem('Recuerdo de Luna','🌙');save();updateUI();notify('+25 monedas · nueva misión');say('Luna: “Gracias. Llegó justo cuando debía. Quedate con este recuerdo. Y si pasás por el almacén, comprame un pan.”');return}if(state.quest==='none'){say('Luna: “Hola. ¿Recién llegás? Hablá con el Vecino.”');return}if(state.quest==='letter'){say('Luna: “Creo que el Vecino quería decirme algo. ¿Encontraste la carta?”');return}if(state.quest==='bread'){say('Luna: “¿Pudiste conseguir el pan en el almacén?”');return}say('Luna: “Hay muchas historias escondidas acá.”');return}
 say('Almacenero: “Bienvenido. El pueblo siempre necesita una mano.”')
}
function getTarget(){let target=null,best=.085;npcs.forEach(n=>{const d=Math.hypot(x-n.x,y-n.y);if(d<best){best=d;target={type:'npc',data:n}}});if(!state.letterTaken){const d=Math.hypot(x-.34,y-.29);if(d<best){best=d;target={type:'letter'}}}if(state.quest==='bread'&&!state.breadTaken){const d=Math.hypot(x-.76,y-.58);if(d<best)target={type:'bread'}}return target}
function loop(t){let dx=0,dy=0;if(!dialogueOpen&&!inventory.classList.contains('hidden')){}else if(!dialogueOpen){if(keys.w||keys.arrowup)dy-=.0045;if(keys.s||keys.arrowdown)dy+=.0045;if(keys.a||keys.arrowleft)dx-=.0045;if(keys.d||keys.arrowright)dx+=.0045;if(dx&&dy){dx*=.707;dy*=.707}move(dx,dy)}player.style.left=x*100+'%';player.style.top=y*100+'%';const target=getTarget();if(target&&!dialogueOpen){interaction.style.display='block';interaction.textContent=target.type==='letter'?'E — Recoger carta':target.type==='bread'?'E — Comprar pan (5 🪙)':'E — Hablar con '+target.data.name;if(keys.e){interact();keys.e=false}}else interaction.style.display='none';if(t-lastSave>1000){save();lastSave=t}requestAnimationFrame(loop)}
updateUI();requestAnimationFrame(loop);