/* LUNA PELÓN — HISTORIA VIVA · NÚCLEO 1.1
   Motor: estado único → escenas → entidades → interacción → misiones → memoria → guardado.
   Sin dependencias externas. Todo corre en navegador.
*/
const $=id=>document.getElementById(id);
const UI={menu:$('menu'),game:$('game'),play:$('playButton'),newGame:$('newGameButton'),world:$('world'),map:$('worldMap'),player:$('player'),interaction:$('interaction'),dialogue:$('dialogue'),questTitle:$('questTitle'),questObjective:$('questObjective'),progress:$('progressText'),coins:$('coinLabel'),day:$('dayLabel'),chapter:$('chapterLabel'),letter:$('letter'),bread:$('bread'),artifact:$('artifact'),toast:$('toast'),journal:$('journal'),journalButton:$('journalButton'),closeJournal:$('closeJournal'),journalContent:$('journalContent'),inventory:$('inventory'),inventoryButton:$('inventoryButton'),closeInventory:$('closeInventory'),inventoryItems:$('inventoryItems'),history:$('historyCard'),historyTitle:$('historyTitle'),historyText:$('historyText'),historySource:$('historySource'),closeHistory:$('closeHistory'),interior:$('interior'),interiorTitle:$('interiorTitle'),interiorKicker:$('interiorKicker'),interiorContent:$('interiorContent'),interiorAction:$('interiorAction'),exitInterior:$('exitInterior')};
const SAVE_KEY='luna-pelon-save-v11',OLD_KEYS=['luna-pelon-save-v10','luna-pelon-save-v09','luna-pelon-save-v08','luna-pelon-save-v07'];
const WORLD={w:1800,h:1050};
const DEFAULTS={x:.50,y:.52,coins:0,inventory:[],quest:'intro',memories:[],day:1,chapter:1,zone:'village',visited:[],interiors:{},flags:{},version:11};
const CHAPTERS={1:{title:'El territorio',short:'Antes de las calles'},2:{title:'El agua abre camino',short:'Acequia y riego'},3:{title:'Las chacras',short:'Tierra y cosecha'},4:{title:'Nace una comunidad',short:'Fecha y memoria'},5:{title:'Voces del presente',short:'Muchas historias'}};
const MEMORIES={river:{chapter:1,title:'El río y la vida',text:'Los valles irrigados transformaron paisajes áridos en zonas de producción. El agua, los canales y el trabajo son parte esencial de esta historia territorial.',source:'Recreación educativa inspirada en documentación pública provincial.'},irrigation:{chapter:2,title:'El agua no llega sola',text:'La agricultura necesita infraestructura: canales, compuertas, drenajes y mantenimiento. El riego modifica el territorio y permite sostener chacras productivas.',source:'Recreación educativa inspirada en documentación pública de infraestructura y ordenamiento.'},orchard:{chapter:3,title:'De la tierra a la cosecha',text:'El paisaje productivo se organiza en parcelas, caminos, alamedas y chacras. La producción frutícola y vitivinícola forma parte del desarrollo regional.',source:'Recreación educativa inspirada en documentación ambiental y territorial pública.'},founding:{chapter:4,title:'Cuando nace una comunidad',text:'Una fecha fundacional marca un momento de organización, pero no contiene toda la historia. Antes y después existen familias, trabajo, territorio, agua y decisiones.',source:'Recreación narrativa educativa; no es una reproducción documental.'},people:{chapter:5,title:'Muchas historias, un territorio',text:'La memoria rural reúne voces indígenas, criollas, familias llegadas de distintos lugares y trabajadores vinculados a las actividades productivas. Una historia local no tiene una sola voz.',source:'Recreación educativa inspirada en documentación territorial pública.'}};
const NPCS={neighbor:{id:'neighbor',name:'Vecino',x:.42,y:.42,home:[.42,.42],speed:.00055,voice:'Si querés conocer este lugar, mirá el agua, las chacras y escuchá a la gente.'},shopkeeper:{id:'shopkeeper',name:'Almacenero',x:.83,y:.55,home:[.83,.55],speed:.00035,voice:'Un almacén no vende solamente cosas: también hace circular noticias.'},teacher:{id:'teacher',name:'Maestra',x:.59,y:.76,home:[.59,.76],speed:.00045,voice:'Aprender historia también es aprender a mirar el territorio.'}};
const DOORS={house:{id:'house',name:'Casa de Luna',x:.19,y:.31,spawn:[.19,.36]},store:{id:'store',name:'Almacén',x:.74,y:.59,spawn:[.74,.64]},school:{id:'school',name:'Escuela',x:.58,y:.75,spawn:[.58,.80]}};
const PLACES={river:{id:'river',name:'Río',x:.89,y:.35,r:.07},orchard:{id:'orchard',name:'Chacras',x:.14,y:.68,r:.09}};
const OBSTACLES=[{x:.09,y:.18,w:.20,h:.17},{x:.68,y:.46,w:.18,h:.15},{x:.51,y:.67,w:.14,h:.13},{x:.22,y:.60,w:.09,h:.14},{x:.77,y:.68,w:.11,h:.14}];
const keys={};let state=loadState(),x=state.x,y=state.y,last=performance.now(),lastSave=0,dialogueOpen=false,historyOpen=false,currentInterior=null,started=false,frame=0;
function fresh(){return JSON.parse(JSON.stringify(DEFAULTS))}
function normalize(s){const d=fresh(),out={...d,...s};out.inventory=Array.isArray(out.inventory)?out.inventory:[];out.memories=Array.isArray(out.memories)?out.memories:[];out.visited=Array.isArray(out.visited)?out.visited:[];out.interiors=out.interiors&&typeof out.interiors==='object'?out.interiors:{};out.flags=out.flags&&typeof out.flags==='object'?out.flags:{};out.chapter=Math.min(5,Math.max(1,Number(out.chapter)||1));out.day=Math.max(1,Number(out.day)||1);out.x=Math.min(1,Math.max(0,Number(out.x)||.5));out.y=Math.min(1,Math.max(0,Number(out.y)||.52));out.quest=String(out.quest||'intro');out.version=11;return out}
function loadState(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw)for(const k of OLD_KEYS){raw=localStorage.getItem(k);if(raw)break}return raw?normalize(JSON.parse(raw)):fresh()}catch(e){console.warn('Guardado no disponible',e);return fresh()}}
function save(force=false){const now=Date.now();if(!force&&now-lastSave<500)return;state.x=x;state.y=y;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));lastSave=now}catch(e){notify('No se pudo guardar la partida en este navegador.')}}
function has(name){return state.inventory.some(i=>i.name===name)}
function addItem(name,icon){if(!has(name)){state.inventory.push({name,icon});updateUI();save(true)}}
function removeItem(name){state.inventory=state.inventory.filter(i=>i.name!==name);updateUI();save(true)}
function notify(text){UI.toast.textContent=text;UI.toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>UI.toast.classList.remove('show'),2200)}
function say(text){UI.dialogue.textContent=text;UI.dialogue.style.display='block';dialogueOpen=true}
function closeDialogue(){UI.dialogue.style.display='none';dialogueOpen=false}
function setChapter(n){if(n>state.chapter){state.chapter=Math.min(5,n);notify('Nuevo capítulo: '+CHAPTERS[state.chapter].title);updateUI();save(true)}}
function learn(id){const m=MEMORIES[id];if(!m||state.memories.includes(id))return false;state.memories.push(id);setChapter(m.chapter);updateUI();save(true);UI.historyTitle.textContent=m.title;UI.historyText.textContent=m.text;UI.historySource.textContent=m.source;UI.history.classList.remove('hidden');historyOpen=true;return true}
function visit(id){if(!state.visited.includes(id)){state.visited.push(id);updateUI();save(true)}}
function questData(){return{intro:['El primer recorrido','Hablá con el Vecino.','1 / 6'],letter:['Un mensaje','Encontrá la carta cerca de la casa del Vecino.','2 / 6'],deliver:['Una historia que viaja','Llevá la carta a la Maestra.','3 / 6'],bread:['Una compra sencilla','Comprá un pan en el Almacén por 5 monedas.','4 / 6'],learn:['Las huellas del territorio','Observá la huella junto a la acequia.','5 / 6'],explore:['Voces del pueblo','Hablá con la Maestra y reuní otra memoria.','6 / 6'],done:['Historia en marcha','Explorá el mundo y descubrí sus memorias.','COMPLETADA']}[state.quest]||['Historia en marcha','Explorá.','—']}
function updateUI(){const q=questData();UI.questTitle.textContent=q[0];UI.questObjective.textContent=q[1];UI.progress.textContent=q[2];UI.coins.textContent='🪙 '+state.coins;const period=['NOCHE','MAÑANA','MEDIODÍA','TARDE','ATARDECER'];UI.day.textContent='DÍA '+state.day+' · '+period[(state.day-1)%5];UI.chapter.textContent='CAPÍTULO '+state.chapter+' · '+CHAPTERS[state.chapter].title.toUpperCase();UI.letter.classList.toggle('taken',has('Carta'));UI.bread.classList.toggle('taken',has('Pan'));UI.artifact.classList.toggle('taken',has('Huella del territorio'));UI.inventoryItems.innerHTML=state.inventory.length?state.inventory.map(i=>`<div class="inventory-item"><span class="icon">${i.icon}</span><small>${i.name}</small></div>`).join(''):'<div class="inventory-empty">El inventario está vacío.</div>';renderJournal('story')}
function renderJournal(tab='story'){if(tab==='facts'){UI.journalContent.innerHTML=state.memories.length?state.memories.map(id=>{const m=MEMORIES[id];return `<article class="journal-entry"><span class="chapter-mini">CAP. ${m.chapter}</span><strong>${m.title}</strong><p>${m.text}</p></article>`}).join(''):'<article class="journal-entry"><strong>Aún no hay memorias.</strong><p>Caminar, observar y conversar desbloquea el conocimiento.</p></article>';return}if(tab==='map'){UI.journalContent.innerHTML=`<article class="journal-entry"><strong>Rumbo</strong><p>Casa · almacén · escuela · acequia · chacras · río.</p></article><article class="journal-entry"><strong>Capítulos</strong><p>${Object.entries(CHAPTERS).map(([n,c])=>`CAP. ${n} · ${c.title} ${+n<=state.chapter?'✓':'· pendiente'}`).join('<br>')}</p></article><article class="journal-entry"><strong>Exploración</strong><p>${state.visited.length} lugares registrados · ${Object.keys(state.interiors).length} interiores visitados.</p></article>`;return}if(tab==='settings'){UI.journalContent.innerHTML='<article class="journal-entry"><strong>Partida</strong><p>El progreso se guarda automáticamente en este dispositivo.</p><button id="resetSave" class="danger-button">BORRAR PARTIDA Y EMPEZAR DE NUEVO</button></article>';const b=$('resetSave');if(b)b.onclick=resetSave;return}UI.journalContent.innerHTML=`<article class="journal-entry"><span class="chapter-mini">PROTAGONISTA</span><strong>Luna</strong><p>La historia se reconstruye caminando, observando, conversando y entrando a espacios cotidianos.</p></article><article class="journal-entry"><strong>Memorias</strong><p>${state.memories.length} de ${Object.keys(MEMORIES).length} descubiertas.</p></article><article class="journal-entry"><strong>Estado</strong><p>Capítulo ${state.chapter} · Día ${state.day} · ${state.visited.length} lugares descubiertos.</p></article>`}
function resetSave(){if(!confirm('¿Borrar toda la partida y empezar desde el principio?'))return;try{localStorage.removeItem(SAVE_KEY)}catch(e){}state=fresh();x=state.x;y=state.y;currentInterior=null;UI.journal.classList.add('hidden');UI.inventory.classList.add('hidden');UI.interior.classList.add('hidden');closeDialogue();updateUI();placePlayer();notify('Partida nueva creada')}
function openPanel(p){closeDialogue();p.classList.remove('hidden')}
function closePanel(p){p.classList.add('hidden')}
function interiorData(kind){return{house:{k:'CASA',t:'Casa de Luna',action:'LEER EL CUADERNO',html:'<div class="interior-object bed">CAMA</div><div class="interior-object table">MESA</div><div class="interior-object notebook">CUADERNO</div><p>Un espacio cotidiano también guarda memoria: objetos, hábitos y relatos forman parte de la vida.</p>'},store:{k:'ALMACÉN',t:'Almacén',action:'MIRAR LA LIBRETA',html:'<div class="interior-object shelf">ESTANTES</div><div class="interior-object counter">MOSTRADOR</div><div class="interior-object ledger">LIBRETA</div><p>Mercaderías, conversaciones y noticias se cruzan en este punto de encuentro.</p>'},school:{k:'ESCUELA',t:'Escuela',action:'ESTUDIAR EL PIZARRÓN',html:'<div class="interior-object board">AGUA → TIERRA → COSECHA</div><div class="interior-object desk">BANCOS</div><p>La escuela transforma observaciones del territorio en preguntas y conocimientos.</p>'}}[kind]}
function enterInterior(kind){const d=interiorData(kind);if(!d)return;currentInterior=kind;state.zone=kind;state.interiors[kind]=true;UI.interiorKicker.textContent=d.k;UI.interiorTitle.textContent=d.t;UI.interiorContent.innerHTML=d.html;UI.interiorAction.textContent=d.action;UI.interior.classList.remove('hidden');visit(kind);save(true)}
function exitInterior(){UI.interior.classList.add('hidden');currentInterior=null;state.zone='village';const d=DOORS[state.lastDoor||'house'];if(d){x=d.spawn[0];y=d.spawn[1]}save(true);placePlayer()}
function interiorInteract(){if(currentInterior==='house'){if(learn('people'))say('Luna: “Una casa también puede ser un archivo de la vida cotidiana.”');else say('Luna: “Ya anoté lo que aprendí acá.”')}else if(currentInterior==='store'){say('Libreta: “Las compras son pequeñas, pero las conversaciones conectan al pueblo.”')}else if(currentInterior==='school'){if(!state.memories.includes('irrigation'))learn('irrigation');else if(!state.memories.includes('orchard'))learn('orchard');else say('Luna: “Esta parte ya está en mi diario.”')}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function target(){if(currentInterior)return null;let best=.055,t=null;Object.values(NPCS).forEach(n=>{const d=dist({x,y},n);if(d<best){best=d;t={type:'npc',data:n,label:'E — hablar con '+n.name}}});Object.values(DOORS).forEach(d=>{const q=dist({x,y},d);if(q<best){best=q;t={type:'door',data:d,label:'E — entrar en '+d.name}}});const objs=[!has('Carta')&&{type:'letter',x:.34,y:.29,label:'E — recoger carta'},state.quest==='bread'&&!has('Pan')&&{type:'bread',x:.76,y:.58,label:'E — comprar pan · 5 monedas'},!has('Huella del territorio')&&{type:'artifact',x:.28,y:.78,label:'E — observar huella'}].filter(Boolean);objs.forEach(o=>{const d=dist({x,y},o);if(d<best){best=d;t={type:o.type,data:o,label:o.label}}});Object.values(PLACES).forEach(o=>{const d=dist({x,y},o);if(d<Math.min(best,o.r)){best=d;t={type:o.type,data:o,label:'E — '+(o.id==='river'?'contemplar el río':'observar las chacras')}}});return t}
function interact(){if(currentInterior){interiorInteract();return}const t=target();if(!t){say('Luna: “Tengo que acercarme un poco más.”');return}if(t.type==='door'){state.lastDoor=t.data.id;enterInterior(t.data.id);return}if(t.type==='letter'){addItem('Carta','✉️');state.quest='deliver';notify('Carta encontrada');say('Luna: “La llevo a la Maestra.”');return}if(t.type==='bread'){if(state.coins<5)return say('Almacenero: “Te faltan monedas. Volvé cuando tengas 5.”');state.coins-=5;addItem('Pan','🥖');state.quest='learn';state.day++;setChapter(2);notify('Pan comprado · -5 monedas');say('Almacenero: “Un pan, una charla y un camino.”');return}if(t.type==='artifact'){addItem('Huella del territorio','🪨');state.quest='explore';learn('irrigation');return}if(t.type==='river'){visit('river');learn('river');return}if(t.type==='orchard'){visit('orchard');if(state.chapter>=3)learn('orchard');else say('Luna: “Agua, suelo y trabajo parecen formar un mismo sistema.”');return}const n=t.data;if(n.id==='neighbor'){if(state.quest==='intro'){state.quest='letter';learn('founding');say('Vecino: '+n.voice+' Tengo una carta para la Maestra.')}else say('Vecino: “Ninguna historia empieza solamente cuando alguien pone una fecha.”');return}if(n.id==='teacher'){if(state.quest==='deliver'&&has('Carta')){removeItem('Carta');state.quest='bread';state.coins+=25;notify('+25 monedas');say('Maestra: “Gracias, Luna. Ahora recorré el pueblo con otros ojos.”')}else if(state.quest==='explore'){state.quest='done';learn('people');say('Maestra: “La memoria se construye escuchando más de una voz.”')}else say(n.voice);return}if(n.id==='shopkeeper')say(n.voice)}
function blocked(nx,ny){const m=.018;if(nx<m||nx>1-m||ny<m||ny>1-m)return true;return OBSTACLES.some(o=>{const cx=Math.max(o.x,Math.min(nx,o.x+o.w)),cy=Math.max(o.y,Math.min(ny,o.y+o.h));return Math.hypot(nx-cx,ny-cy)<m})}
function move(dt){if(!started||currentInterior||dialogueOpen||historyOpen||!UI.journal.classList.contains('hidden')||!UI.inventory.classList.contains('hidden'))return;let dx=(keys.arrowright||keys.d?1:0)-(keys.arrowleft||keys.a?1:0),dy=(keys.arrowdown||keys.s?1:0)-(keys.arrowup||keys.w?1:0);if(!dx&&!dy)return;const len=Math.hypot(dx,dy),speed=.00034*dt,nx=x+dx/len*speed,ny=y+dy/len*speed;if(!blocked(nx,y))x=nx;if(!blocked(x,ny))y=ny;placePlayer();save()}
function updateNPCs(dt){const cycle=Math.floor(Date.now()/9000)%4;Object.entries(NPCS).forEach(([id,n])=>{let tx=n.home[0],ty=n.home[1];if(cycle===1){if(id==='shopkeeper'){tx=.78;ty=.54}else if(id==='teacher'){tx=.56;ty=.69}else{tx=.47;ty=.44}}else if(cycle===2){if(id==='neighbor'){tx=.34;ty=.56}else if(id==='shopkeeper'){tx=.70;ty=.50}else{tx=.61;ty=.68}}else if(cycle===3){if(id==='neighbor'){tx=.48;ty=.63}else if(id==='shopkeeper'){tx=.81;ty=.62}else{tx=.54;ty=.77}}const step=n.speed*dt,dx=tx-n.x,dy=ty-n.y,d=Math.hypot(dx,dy);if(d>.001){n.x+=dx/d*Math.min(step,d);n.y+=dy/d*Math.min(step,d)}const el=document.querySelector(`[data-npc="${id}"]`);if(el){el.style.left=(n.x*100)+'%';el.style.top=(n.y*100)+'%'}})}
function placePlayer(){UI.player.style.left=(x*100)+'%';UI.player.style.top=(y*100)+'%';const vw=Math.min(innerWidth,WORLD.w),vh=Math.min(innerHeight-62,WORLD.h);const camX=Math.min(0,Math.max(-(WORLD.w-vw),vw*.5-x*WORLD.w));const camY=Math.min(0,Math.max(-(WORLD.h-vh),vh*.48-y*WORLD.h));UI.map.style.transform=`translate(${camX}px,${camY}px)`}
function render(){if(frame++%8===0)updateUI();placePlayer();const t=target();UI.interaction.textContent=t?t.label:'';UI.interaction.style.display=t?'block':'none';UI.world.classList.toggle('evening',((state.day-1)%5)>=3)}
function loop(now){const dt=Math.min(48,now-last);last=now;move(dt);updateNPCs(dt);render();requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='e'&&!e.repeat)interact();if(k==='i'&&!e.repeat)openPanel(UI.inventory);if(k==='j'&&!e.repeat)openPanel(UI.journal);if(k==='escape'){if(currentInterior)exitInterior();else if(!UI.inventory.classList.contains('hidden'))closePanel(UI.inventory);else if(!UI.journal.classList.contains('hidden'))closePanel(UI.journal);else if(historyOpen){UI.history.classList.add('hidden');historyOpen=false}else closeDialogue()}});window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false});document.querySelectorAll('.touch-controls [data-key]').forEach(b=>{const k=b.dataset.key,on=e=>{e.preventDefault();keys[k]=true;if(k==='e')interact()},off=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});
UI.play.onclick=()=>start(false);UI.newGame.onclick=()=>start(true);UI.journalButton.onclick=()=>openPanel(UI.journal);UI.closeJournal.onclick=()=>closePanel(UI.journal);UI.inventoryButton.onclick=()=>openPanel(UI.inventory);UI.closeInventory.onclick=()=>closePanel(UI.inventory);UI.closeHistory.onclick=()=>{UI.history.classList.add('hidden');historyOpen=false};UI.exitInterior.onclick=exitInterior;UI.interiorAction.onclick=interiorInteract;UI.dialogue.onclick=closeDialogue;document.querySelectorAll('.journal-tabs button').forEach(b=>b.onclick=()=>renderJournal(b.dataset.tab));window.addEventListener('beforeunload',()=>save(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)save(true)});
function start(isNew=false){if(isNew){state=fresh();x=state.x;y=state.y;try{localStorage.removeItem(SAVE_KEY)}catch(e){}}started=true;UI.menu.classList.add('hidden');UI.game.classList.remove('hidden');updateUI();placePlayer();notify(isNew?'Nueva partida':'Partida cargada')}
updateUI();requestAnimationFrame(loop);