/* LUNA PELÓN — HISTORIA VIVA · RPG 2.0 · CORE STABLE */
const $=id=>document.getElementById(id);
const UI={menu:$('menu'),game:$('game'),play:$('playButton'),newGame:$('newGameButton'),intro:$('introCinematic'),introStart:$('introStart'),world:$('world'),map:$('worldMap'),player:$('player'),interaction:$('interaction'),dialogue:$('dialogue'),questTitle:$('questTitle'),questObjective:$('questObjective'),progress:$('progressText'),reward:$('questReward'),coins:$('coinLabel'),day:$('dayLabel'),chapter:$('chapterLabel'),level:$('levelLabel'),xp:$('xpBar'),letter:$('letter'),bread:$('bread'),artifact:$('artifact'),toast:$('toast'),journal:$('journal'),journalButton:$('journalButton'),closeJournal:$('closeJournal'),journalContent:$('journalContent'),inventory:$('inventory'),inventoryButton:$('inventoryButton'),closeInventory:$('closeInventory'),inventoryItems:$('inventoryItems'),history:$('historyCard'),historyTitle:$('historyTitle'),historyText:$('historyText'),historySource:$('historySource'),closeHistory:$('closeHistory'),interior:$('interior'),interiorTitle:$('interiorTitle'),interiorKicker:$('interiorKicker'),interiorContent:$('interiorContent'),interiorAction:$('interiorAction'),exitInterior:$('exitInterior'),banner:$('sceneBanner'),bannerKicker:$('sceneKicker'),bannerTitle:$('sceneTitle')};
/* V2 uses an isolated save namespace so saves from later experimental builds cannot contaminate the stable core. */
const SAVE_KEY='luna-pelon-rpg2-stable',LEGACY_KEYS=['luna-pelon-save-v20','luna-pelon-save-v11','luna-pelon-save-v10','luna-pelon-save-v09','luna-pelon-save-v08','luna-pelon-save-v07'];
const WORLD={w:1800,h:1050};
const DEFAULTS={x:.50,y:.52,coins:0,xp:0,inventory:[],quest:'intro',memories:[],day:1,chapter:1,zone:'village',visited:[],interiors:{},flags:{},version:20};
const CHAPTERS={1:{title:'El territorio',short:'Antes de las calles',xp:20},2:{title:'El agua abre camino',short:'Acequia y riego',xp:30},3:{title:'Las chacras',short:'Tierra y cosecha',xp:40},4:{title:'Nace una comunidad',short:'Fecha y memoria',xp:50},5:{title:'Voces del presente',short:'Muchas historias',xp:60}};
const MEMORIES={river:{chapter:1,title:'El río y la vida',text:'El agua organiza el territorio. Los valles irrigados pueden sostener producción, caminos y asentamientos cuando existe infraestructura y trabajo.',source:'Recreación educativa inspirada en documentación territorial pública.'},irrigation:{chapter:2,title:'El agua no llega sola',text:'Acequias, canales, compuertas y drenajes requieren organización y mantenimiento. El riego transforma un paisaje y permite sostener chacras productivas.',source:'Recreación educativa inspirada en documentación pública de infraestructura.'},orchard:{chapter:3,title:'De la tierra a la cosecha',text:'Parcelas, alamedas, caminos y chacras forman un paisaje productivo. La producción frutícola y vitivinícola dejó huellas profundas en la vida regional.',source:'Recreación educativa inspirada en documentación territorial pública.'},founding:{chapter:4,title:'Una fecha no contiene toda la historia',text:'Una fecha de fundación marca un momento institucional. La historia del territorio es más amplia: incluye personas, trabajo, agua, decisiones y formas de habitar anteriores y posteriores.',source:'Recreación narrativa educativa; no es reproducción documental.'},people:{chapter:5,title:'Muchas voces, un territorio',text:'La memoria reúne voces indígenas, criollas, familias llegadas de distintos lugares y trabajadores ligados a actividades productivas. Una historia local no tiene una sola voz.',source:'Recreación educativa inspirada en documentación territorial pública.'}};
const NPCS={neighbor:{id:'neighbor',name:'Vecino',x:.42,y:.42,home:[.42,.42],speed:.00055,zone:'village',voice:'Si querés conocer este lugar, mirá el agua, las chacras y escuchá a la gente.'},shopkeeper:{id:'shopkeeper',name:'Almacenero',x:.83,y:.55,home:[.83,.55],speed:.00035,zone:'street',voice:'Un almacén no vende solamente cosas: también hace circular noticias.'},teacher:{id:'teacher',name:'Maestra',x:.59,y:.76,home:[.59,.76],speed:.00045,zone:'village',voice:'Aprender historia también es aprender a mirar el territorio.'},farmer:{id:'farmer',name:'Trabajador rural',x:.48,y:.25,home:[.48,.25],speed:.00030,zone:'rural',voice:'En el campo se aprende rápido: si falta agua, todo lo demás se complica.'}};
const DOORS={house:{id:'house',name:'Casa de Luna',x:.19,y:.31,spawn:[.19,.36]},store:{id:'store',name:'Almacén',x:.74,y:.59,spawn:[.74,.64]},school:{id:'school',name:'Escuela',x:.58,y:.75,spawn:[.58,.80]}};
const PLACES={river:{id:'river',name:'Río',x:.89,y:.35,r:.07},orchard:{id:'orchard',name:'Chacras',x:.14,y:.68,r:.09},bridge:{id:'bridge',name:'Puente',x:.87,y:.49,r:.055},farm:{id:'farm',name:'Campo rural',x:.52,y:.25,r:.12}};
const OBSTACLES=[{x:.09,y:.18,w:.20,h:.17},{x:.68,y:.46,w:.18,h:.15},{x:.51,y:.67,w:.14,h:.13},{x:.22,y:.60,w:.09,h:.14},{x:.77,y:.68,w:.11,h:.14}];
const keys={};let state=loadState(),x=state.x,y=state.y,last=performance.now(),lastSave=0,dialogueOpen=false,historyOpen=false,currentInterior=null,started=false,frame=0,lastJournalTab='story';
function fresh(){return JSON.parse(JSON.stringify(DEFAULTS))}
function normalize(s){const d=fresh(),o={...d,...(s&&typeof s==='object'?s:{})};o.inventory=Array.isArray(o.inventory)?o.inventory.filter(i=>i&&typeof i.name==='string').map(i=>({name:i.name,icon:String(i.icon||'•')})):[];o.memories=Array.isArray(o.memories)?o.memories.filter(id=>MEMORIES[id]):[];o.visited=Array.isArray(o.visited)?o.visited.filter(Boolean):[];o.interiors=o.interiors&&typeof o.interiors==='object'?o.interiors:{};o.flags=o.flags&&typeof o.flags==='object'?o.flags:{};o.chapter=Math.min(5,Math.max(1,Number(o.chapter)||1));o.day=Math.max(1,Number(o.day)||1);o.coins=Math.max(0,Number(o.coins)||0);o.xp=Math.max(0,Number(o.xp)||0);o.x=Math.min(1,Math.max(0,Number(o.x)||.5));o.y=Math.min(1,Math.max(0,Number(o.y)||.52));o.quest=QUESTS&&QUESTS[o.quest]?o.quest:'intro';o.version=20;return o}
function loadState(){try{let raw=localStorage.getItem(SAVE_KEY);if(raw)return normalize(JSON.parse(raw));/* Only import the previous stable V2 schema, never experimental life-system saves. */raw=localStorage.getItem('luna-pelon-save-v20');if(raw){const parsed=JSON.parse(raw);return normalize(parsed)}return fresh()}catch(e){return fresh()}}
function save(force=false){const now=Date.now();if(!force&&now-lastSave<500)return;state.x=x;state.y=y;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));lastSave=now}catch(e){notify('No se pudo guardar la partida en este navegador.')}}
function has(name){return state.inventory.some(i=>i.name===name)}
function addItem(name,icon){if(!has(name)){state.inventory.push({name,icon});updateUI();save(true)}}
function removeItem(name){state.inventory=state.inventory.filter(i=>i.name!==name);updateUI();save(true)}
function notify(text){if(!UI.toast)return;UI.toast.textContent=text;UI.toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>UI.toast.classList.remove('show'),2200)}
function say(text){UI.dialogue.textContent=text;UI.dialogue.style.display='block';dialogueOpen=true}
function closeDialogue(){UI.dialogue.style.display='none';dialogueOpen=false}
function level(){return 1+Math.floor(state.xp/100)}
function gainXP(n,reason){const old=level();state.xp+=Math.max(0,Number(n)||0);const now=level();if(now>old)notify('¡Subiste a nivel '+now+'!');else if(reason)notify('+'+n+' XP · '+reason);updateUI();save(true)}
function setChapter(n){if(n>state.chapter){state.chapter=Math.min(5,n);showBanner('NUEVO CAPÍTULO',CHAPTERS[state.chapter].title);gainXP(CHAPTERS[state.chapter].xp,'capítulo desbloqueado')}}
function learn(id){const m=MEMORIES[id];if(!m||state.memories.includes(id))return false;state.memories.push(id);UI.historyTitle.textContent=m.title;UI.historyText.textContent=m.text;UI.historySource.textContent=m.source;UI.history.classList.remove('hidden');historyOpen=true;gainXP(15,'memoria descubierta');return true}
function visit(id){if(!state.visited.includes(id)){state.visited.push(id);gainXP(5,'nuevo lugar')}}
function showBanner(kicker,title){UI.bannerKicker.textContent=kicker;UI.bannerTitle.textContent=title;UI.banner.classList.add('show');clearTimeout(showBanner.timer);showBanner.timer=setTimeout(()=>UI.banner.classList.remove('show'),2800)}
const QUESTS={intro:{title:'El primer recorrido',objective:'Hablá con el Vecino y aceptá conocer el territorio.',progress:'1 / 8',reward:'+10 XP'},letter:{title:'Una historia que viaja',objective:'Encontrá la carta cerca de la casa del Vecino.',progress:'2 / 8',reward:'+10 XP'},deliver:{title:'Una historia que viaja',objective:'Llevá la carta a la Maestra en la escuela.',progress:'3 / 8',reward:'+20 XP'},bread:{title:'La vida cotidiana',objective:'Conseguí un pan en el Almacén. Tenés 25 monedas.',progress:'4 / 8',reward:'+15 XP'},learn:{title:'El agua abre camino',objective:'Seguí la acequia y observá la huella del territorio.',progress:'5 / 8',reward:'+25 XP'},bridge:{title:'El otro lado',objective:'Llegá al puente y cruzá el río.',progress:'6 / 8',reward:'+30 XP'},rural:{title:'Tierra de trabajo',objective:'Visitá el campo rural y hablá con el Trabajador rural.',progress:'7 / 8',reward:'+35 XP'},explore:{title:'Voces del pueblo',objective:'Volvé a la Maestra para cerrar el primer recorrido.',progress:'8 / 8',reward:'+50 XP'},done:{title:'Historia en marcha',objective:'Explorá libremente. Hay memorias, personas y lugares por descubrir.',progress:'COMPLETADA',reward:'Exploración libre'}};
function questData(){return QUESTS[state.quest]||QUESTS.done}
function updateUI(){const q=questData(),lv=level();UI.questTitle.textContent=q.title;UI.questObjective.textContent=q.objective;UI.progress.textContent=q.progress;UI.reward.textContent=q.reward;UI.coins.textContent='🪙 '+state.coins;UI.level.textContent='NIVEL '+lv;UI.xp.style.width=(state.xp%100)+'%';UI.day.textContent='DÍA '+state.day+' · '+['MAÑANA','MEDIODÍA','TARDE','ATARDECER','NOCHE'][(state.day-1)%5];UI.chapter.textContent='CAPÍTULO '+state.chapter+' · '+CHAPTERS[state.chapter].title.toUpperCase();UI.letter.classList.toggle('taken',has('Carta'));UI.bread.classList.toggle('taken',has('Pan'));UI.artifact.classList.toggle('taken',has('Huella del territorio'));UI.inventoryItems.innerHTML=state.inventory.length?state.inventory.map(i=>`<div class="inventory-item"><span class="icon">${i.icon}</span><small>${i.name}</small></div>`).join(''):'<div class="inventory-empty">El inventario está vacío.</div>';renderJournal(lastJournalTab)}
function renderJournal(tab=lastJournalTab){lastJournalTab=tab;if(tab==='facts'){UI.journalContent.innerHTML=state.memories.length?state.memories.map(id=>{const m=MEMORIES[id];return `<article class="journal-entry"><span class="chapter-mini">CAP. ${m.chapter}</span><strong>${m.title}</strong><p>${m.text}</p></article>`}).join(''):'<article class="journal-entry"><strong>Aún no hay memorias.</strong><p>Las descubrís caminando, observando y conversando.</p></article>';return}if(tab==='map'){UI.journalContent.innerHTML=`<article class="journal-entry"><strong>Rumbo</strong><p>Casa · almacén · escuela · acequia · chacras · campo · río · puente.</p></article><article class="journal-entry"><strong>Capítulos</strong><p>${Object.entries(CHAPTERS).map(([n,c])=>`CAP. ${n} · ${c.title} ${+n<=state.chapter?'✓':'· pendiente'}`).join('<br>')}</p></article><article class="journal-entry"><strong>Exploración</strong><p>${state.visited.length} lugares registrados · ${Object.keys(state.interiors).length} interiores visitados.</p></article>`;return}if(tab==='settings'){UI.journalContent.innerHTML='<article class="journal-entry"><strong>Partida RPG</strong><p>Nivel '+level()+' · '+state.xp+' XP · Día '+state.day+'. El progreso se guarda automáticamente.</p><button id="resetSave" class="danger-button">BORRAR PARTIDA Y EMPEZAR DE NUEVO</button></article>';const b=$('resetSave');if(b)b.onclick=resetSave;return}UI.journalContent.innerHTML=`<article class="journal-entry"><span class="chapter-mini">PROTAGONISTA</span><strong>Luna</strong><p>Explora un territorio vivo, cumple misiones, conoce personas y reconstruye la memoria con acciones.</p></article><article class="journal-entry"><strong>Memorias</strong><p>${state.memories.length} de ${Object.keys(MEMORIES).length} descubiertas.</p></article><article class="journal-entry"><strong>Estado</strong><p>Nivel ${level()} · Capítulo ${state.chapter} · Día ${state.day} · ${state.visited.length} lugares.</p></article>`}
function resetSave(){if(!confirm('¿Borrar toda la partida y empezar desde el principio?'))return;try{localStorage.removeItem(SAVE_KEY)}catch(e){}state=fresh();x=state.x;y=state.y;currentInterior=null;UI.journal.classList.add('hidden');UI.inventory.classList.add('hidden');UI.interior.classList.add('hidden');UI.intro.classList.add('hidden');closeDialogue();updateUI();placePlayer();save(true);notify('Nueva partida creada')}
function openPanel(p){closeDialogue();p.classList.remove('hidden')}
function closePanel(p){p.classList.add('hidden')}
function interiorData(kind){return{house:{k:'CASA',t:'Casa de Luna',action:'LEER EL CUADERNO',html:'<div class="interior-object bed">CAMA</div><div class="interior-object table">MESA</div><div class="interior-object notebook">CUADERNO</div><p>Los objetos cotidianos también guardan memoria. Luna registra lo que observa para no perder los detalles.</p>'},store:{k:'ALMACÉN',t:'Almacén',action:'MIRAR LA LIBRETA',html:'<div class="interior-object shelf">ESTANTES</div><div class="interior-object counter">MOSTRADOR</div><div class="interior-object ledger">LIBRETA</div><p>Mercaderías, conversaciones y noticias se cruzan en este punto de encuentro.</p>'},school:{k:'ESCUELA',t:'Escuela',action:'ESTUDIAR EL PIZARRÓN',html:'<div class="interior-object board">AGUA → TIERRA → COSECHA</div><div class="interior-object desk">BANCOS</div><p>La escuela convierte lo observado en preguntas y conocimientos.</p>'}}[kind]}
function enterInterior(kind){const d=interiorData(kind);if(!d)return;currentInterior=kind;state.zone=kind;state.interiors[kind]=true;state.lastDoor=kind;UI.interiorKicker.textContent=d.k;UI.interiorTitle.textContent=d.t;UI.interiorContent.innerHTML=d.html;UI.interiorAction.textContent=d.action;UI.interior.classList.remove('hidden');visit(kind);save(true)}
function exitInterior(){UI.interior.classList.add('hidden');currentInterior=null;state.zone='village';const d=DOORS[state.lastDoor||'house'];if(d){x=d.spawn[0];y=d.spawn[1]}save(true);placePlayer()}
function interiorInteract(){if(currentInterior==='house'){if(learn('people'))say('Luna: “Una casa también puede ser un archivo de la vida cotidiana.”');else say('Luna: “Ya anoté lo que aprendí acá.”')}else if(currentInterior==='store'){say('Libreta: “Las compras son pequeñas, pero las conversaciones conectan al pueblo.”')}else if(currentInterior==='school'){if(!state.memories.includes('irrigation'))learn('irrigation');else if(!state.memories.includes('orchard'))learn('orchard');else say('Luna: “Esta parte ya está en mi diario.”')}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function target(){if(currentInterior)return null;let best=.055,t=null;Object.values(NPCS).forEach(n=>{const d=dist({x,y},n);if(d<best){best=d;t={type:'npc',data:n,label:'E — hablar con '+n.name}}});Object.values(DOORS).forEach(d=>{const q=dist({x,y},d);if(q<best){best=q;t={type:'door',data:d,label:'E — entrar en '+d.name}}});const objs=[!has('Carta')&&{type:'letter',x:.34,y:.29,label:'E — recoger carta'},state.quest==='bread'&&!has('Pan')&&{type:'bread',x:.76,y:.58,label:'E — comprar pan · 5 monedas'},state.quest==='learn'&&!has('Huella del territorio')&&{type:'artifact',x:.28,y:.78,label:'E — observar huella'}].filter(Boolean);objs.forEach(o=>{const d=dist({x,y},o);if(d<best){best=d;t={type:o.type,data:o,label:o.label}}});Object.values(PLACES).forEach(o=>{const d=dist({x,y},o);if(d<Math.min(best,o.r)){best=d;t={type:o.id,data:o,label:'E — '+({river:'contemplar el río',orchard:'observar las chacras',bridge:'cruzar el puente',farm:'recorrer el campo rural'}[o.id])}}});return t}
function interact(){if(currentInterior){interiorInteract();return}const t=target();if(!t)return say('Luna: “Tengo que acercarme un poco más.”');if(t.type==='door'){enterInterior(t.data.id);return}if(t.type==='letter'){addItem('Carta','✉️');state.quest='deliver';gainXP(10,'misión avanzada');say('Luna: “La llevo a la Maestra.”');return}if(t.type==='bread'){if(state.coins<5)return say('Almacenero: “Te faltan monedas. Volvé cuando tengas 5.”');state.coins-=5;addItem('Pan','🥖');state.quest='learn';state.day++;setChapter(2);gainXP(15,'compra cotidiana');say('Almacenero: “Un pan, una charla y un camino.”');return}if(t.type==='artifact'){addItem('Huella del territorio','🪨');state.quest='bridge';learn('irrigation');return}if(t.type==='river'){visit('river');learn('river');return}if(t.type==='orchard'){visit('orchard');if(state.chapter>=3)learn('orchard');else say('Luna: “Agua, suelo y trabajo parecen formar un mismo sistema.”');return}if(t.type==='bridge'){visit('bridge');if(state.quest==='bridge'){state.flags.bridgeCrossed=true;state.quest='rural';setChapter(3);gainXP(30,'puente cruzado');say('Luna: “Del otro lado, el paisaje cambia. Hay que mirar cómo continúa el trabajo.”')}else say('Luna: “Este puente conecta dos partes del territorio.”');return}if(t.type==='farm'){visit('farm');if(state.chapter<3)setChapter(3);say('Luna: “El campo no está separado del pueblo. El agua, los caminos y la producción lo conectan todo.”');return}const n=t.data;if(n.id==='neighbor'){if(state.quest==='intro'){state.quest='letter';learn('founding');gainXP(10,'primera misión');say('Vecino: '+n.voice+' Tengo una carta para la Maestra.')}else say('Vecino: “Ninguna historia empieza solamente cuando alguien pone una fecha.”');return}if(n.id==='teacher'){if(state.quest==='deliver'&&has('Carta')){removeItem('Carta');state.quest='bread';state.coins+=25;gainXP(20,'carta entregada');say('Maestra: “Gracias, Luna. Ahora recorré el pueblo con otros ojos.”')}else if(state.quest==='explore'){state.quest='done';learn('people');setChapter(5);gainXP(50,'primer recorrido completado');say('Maestra: “La memoria se construye escuchando más de una voz.”')}else say(n.voice);return}if(n.id==='farmer'){if(state.quest==='rural'){state.quest='explore';learn('orchard');gainXP(35,'misión rural completada');say('Trabajador rural: '+n.voice+' Mirá las chacras: el paisaje cuenta parte de esa historia.')}else say(n.voice);return}if(n.id==='shopkeeper')say(n.voice)}
function blocked(nx,ny){const m=.018;if(nx<m||nx>1-m||ny<m||ny>1-m)return true;if(OBSTACLES.some(o=>{const cx=Math.max(o.x,Math.min(nx,o.x+o.w)),cy=Math.max(o.y,Math.min(ny,o.y+o.h));return Math.hypot(nx-cx,ny-cy)<m}))return true;const riverZone=nx>.835&&nx<.955&&ny>.08&&ny<.70;const bridgePass=ny>.455&&ny<.535;if(riverZone&&!bridgePass)return true;return false}
function move(dt){if(!started||currentInterior||dialogueOpen||historyOpen||!UI.journal.classList.contains('hidden')||!UI.inventory.classList.contains('hidden'))return;let dx=(keys.arrowright||keys.d?1:0)-(keys.arrowleft||keys.a?1:0),dy=(keys.arrowdown||keys.s?1:0)-(keys.arrowup||keys.w?1:0);if(!dx&&!dy)return;const len=Math.hypot(dx,dy),speed=.00034*dt,nx=x+dx/len*speed,ny=y+dy/len*speed;if(!blocked(nx,y))x=nx;if(!blocked(x,ny))y=ny;placePlayer();save()}
function updateNPCs(dt){const cycle=Math.floor(Date.now()/7000)%6;Object.entries(NPCS).forEach(([id,n])=>{let tx=n.home[0],ty=n.home[1];if(id==='farmer'){const p=[[.46,.25],[.54,.23],[.59,.28],[.50,.31],[.44,.28],[.48,.22]][cycle];tx=p[0];ty=p[1]}else if(cycle===1){if(id==='shopkeeper'){tx=.78;ty=.54}else if(id==='teacher'){tx=.56;ty=.69}else if(id==='neighbor'){tx=.47;ty=.44}}else if(cycle===2){if(id==='neighbor'){tx=.34;ty=.56}else if(id==='shopkeeper'){tx=.70;ty=.50}else if(id==='teacher'){tx=.61;ty=.68}}else if(cycle===3){if(id==='neighbor'){tx=.48;ty=.63}else if(id==='shopkeeper'){tx=.81;ty=.62}else if(id==='teacher'){tx=.54;ty=.77}}else if(cycle===4&&id==='teacher'){tx=.58;ty=.72}const step=n.speed*dt,dx=tx-n.x,dy=ty-n.y,d=Math.hypot(dx,dy);if(d>.001){n.x+=dx/d*Math.min(step,d);n.y+=dy/d*Math.min(step,d)}const el=document.querySelector(`[data-npc="${id}"]`);if(el){el.style.left=n.x*100+'%';el.style.top=n.y*100+'%'}})}
function placePlayer(){UI.player.style.left=x*100+'%';UI.player.style.top=y*100+'%';const vw=Math.min(innerWidth,WORLD.w),vh=Math.min(innerHeight-62,WORLD.h),camX=Math.min(0,Math.max(-(WORLD.w-vw),vw*.5-x*WORLD.w)),camY=Math.min(0,Math.max(-(WORLD.h-vh),vh*.48-y*WORLD.h));UI.map.style.transform=`translate(${camX}px,${camY}px)`}
function render(){if(frame++%8===0){const t=target();UI.interaction.textContent=t?t.label:'';UI.interaction.style.display=t?'block':'none';UI.world.classList.toggle('evening',((state.day-1)%5)>=3)}placePlayer()}
function start(isNew=false){if(isNew){state=fresh();x=state.x;y=state.y;try{localStorage.removeItem(SAVE_KEY)}catch(e){}}started=true;UI.menu.classList.add('hidden');UI.game.classList.remove('hidden');if(isNew||state.flags.introSeen!==true)UI.intro.classList.remove('hidden');else UI.intro.classList.add('hidden');updateUI();placePlayer();notify(isNew?'Nueva partida':'Partida cargada')}
UI.play.onclick=()=>start(false);UI.newGame.onclick=()=>start(true);UI.introStart.onclick=()=>{UI.intro.classList.add('hidden');state.flags.introSeen=true;showBanner('PRÓLOGO','El territorio');save(true);say('Luna: “Entonces empieza mi recorrido.”')};UI.journalButton.onclick=()=>openPanel(UI.journal);UI.closeJournal.onclick=()=>closePanel(UI.journal);UI.inventoryButton.onclick=()=>openPanel(UI.inventory);UI.closeInventory.onclick=()=>closePanel(UI.inventory);UI.closeHistory.onclick=()=>{UI.history.classList.add('hidden');historyOpen=false};UI.exitInterior.onclick=exitInterior;UI.interiorAction.onclick=interiorInteract;UI.dialogue.onclick=closeDialogue;document.querySelectorAll('.journal-tabs button').forEach(b=>b.onclick=()=>renderJournal(b.dataset.tab));window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='e'&&!e.repeat)interact();if(k==='i'&&!e.repeat)openPanel(UI.inventory);if(k==='j'&&!e.repeat)openPanel(UI.journal);if(k==='escape'){if(!UI.intro.classList.contains('hidden')){UI.intro.classList.add('hidden');state.flags.introSeen=true;save(true)}else if(currentInterior)exitInterior();else if(!UI.inventory.classList.contains('hidden'))closePanel(UI.inventory);else if(!UI.journal.classList.contains('hidden'))closePanel(UI.journal);else if(historyOpen){UI.history.classList.add('hidden');historyOpen=false}else closeDialogue()}});window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false});document.querySelectorAll('.touch-controls [data-key]').forEach(b=>{const k=b.dataset.key,on=e=>{e.preventDefault();keys[k]=true;if(k==='e')interact()},off=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});window.addEventListener('beforeunload',()=>save(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)save(true)});updateUI();requestAnimationFrame(loop);function loop(now){const dt=Math.min(48,now-last);last=now;move(dt);updateNPCs(dt);render();requestAnimationFrame(loop)}