import {WORLD,NPCS,DISCOVERY,MISSION,VERSION} from './data.js';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const state={x:WORLD.spawn.x,y:WORLD.spawn.y,done:false,seen:false};
const keys=new Set();let touchDir=null,last=performance.now();
const saved=localStorage.getItem('luna-pelon-state-v1');if(saved)Object.assign(state,JSON.parse(saved));
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key===' '){e.preventDefault();interact()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll('#touch button').forEach(b=>{const d=b.dataset.dir;b.addEventListener('pointerdown',e=>{e.preventDefault();touchDir=d});['pointerup','pointercancel','pointerleave'].forEach(t=>b.addEventListener(t,()=>{if(touchDir===d)touchDir=null}))});
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function near(a,b,r=75){return Math.hypot(a.x-b.x,a.y-b.y)<r}
function interact(){for(const n of NPCS)if(near(state,n)){state.done=true;show(`${n.name}: ${n.text}`);save();return}if(near(state,DISCOVERY,90)){state.seen=true;show(`${DISCOVERY.title}\n${DISCOVERY.text}`);save()}}
function show(text){const d=document.querySelector('#dialogue');d.textContent=text;d.classList.remove('hidden');clearTimeout(show.t);show.t=setTimeout(()=>d.classList.add('hidden'),5200)}
function save(){localStorage.setItem('luna-pelon-state-v1',JSON.stringify(state))}
function drawWorld(camX,camY){ctx.fillStyle='#8fb36f';ctx.fillRect(0,0,innerWidth,innerHeight);const s=48;for(let y=0;y<WORLD.height;y+=s)for(let x=0;x<WORLD.width;x+=s){const v=((x/s*17+y/s*31)%7);ctx.fillStyle=v<1?'#86aa68':'#91b873';ctx.fillRect(x-camX,y-camY,s+1,s+1)}
ctx.fillStyle='#5f9fb2';ctx.fillRect(WORLD.river.x-camX,-100-camY,WORLD.river.width,WORLD.height+300);ctx.fillStyle='#b99a6d';ctx.fillRect(-100-camX,650-camY,1800,105);ctx.fillStyle='#d0ae79';ctx.fillRect(1590-camX,650-camY,520,100);ctx.fillStyle='#6f8c52';ctx.fillRect(190-camX,230-camY,420,250);ctx.fillStyle='#6b4a32';ctx.fillRect(270-camX,420-camY,190,150);ctx.fillStyle='#9c5b42';ctx.beginPath();ctx.moveTo(245-camX,420-camY);ctx.lineTo(365-camX,335-camY);ctx.lineTo(485-camX,420-camY);ctx.fill();ctx.fillStyle='#553a2a';ctx.fillRect(342-camX,485-camY,45,85);
for(const n of NPCS){ctx.fillStyle=n.color;ctx.fillRect(n.x-camX-13,n.y-camY-20,26,34);ctx.fillStyle='#d6a074';ctx.fillRect(n.x-camX-10,n.y-camY-35,20,18);ctx.fillStyle='#111';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(n.name,n.x-camX,n.y-camY-44)}
ctx.fillStyle=state.seen?'#777':'#e7d39c';ctx.fillRect(DISCOVERY.x-camX-12,DISCOVERY.y-camY-10,24,20);ctx.fillStyle='#111';ctx.font='10px system-ui';ctx.fillText('MEMORIA',DISCOVERY.x-camX,DISCOVERY.y-camY+4);
ctx.fillStyle='#28486b';ctx.fillRect(state.x-camX-14,state.y-camY-22,28,38);ctx.fillStyle='#d6a074';ctx.fillRect(state.x-camX-10,state.y-camY-38,20,18);ctx.fillStyle='#fff';ctx.font='bold 11px system-ui';ctx.fillText('LUNA',state.x-camX,state.y-camY-47)}
function update(dt){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup')||touchDir==='up')dy--;if(keys.has('s')||keys.has('arrowdown')||touchDir==='down')dy++;if(keys.has('a')||keys.has('arrowleft')||touchDir==='left')dx--;if(keys.has('d')||keys.has('arrowright')||touchDir==='right')dx++;if(dx||dy){const l=Math.hypot(dx,dy);const speed=230;state.x=Math.max(30,Math.min(WORLD.width-30,state.x+dx/l*speed*dt));state.y=Math.max(90,Math.min(WORLD.height-30,state.y+dy/l*speed*dt));for(const n of NPCS)if(near(state,n,52))show(`Presioná ESPACIO para hablar con ${n.name}.`);if(near(state,DISCOVERY,65))show('Presioná ESPACIO para observar la memoria.')} }
function loop(t){const dt=Math.min((t-last)/1000,.05);last=t;update(dt);const camX=Math.max(0,Math.min(WORLD.width-innerWidth,state.x-innerWidth/2));const camY=Math.max(58,Math.min(WORLD.height-innerHeight,state.y-innerHeight/2));ctx.clearRect(0,0,innerWidth,innerHeight);drawWorld(camX,camY);document.querySelector('#objective').textContent=state.done?'Misión completada · explorá':'Misión: '+MISSION.objective;requestAnimationFrame(loop)}requestAnimationFrame(loop);
setInterval(save,3000);